version: "3.8"
services:
    app:
        image: my-nodejs-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
            - DB_URI=mongodb://127.0.0.1:27017/restaurantDB
        restart: unless-stopped
